# Generated by Django 6.0.3 on 2026-04-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_discount_course_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='is_super',
            new_name='can_view',
        ),
    ]
