# Generated by Django 6.0.3 on 2026-04-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('course', '0004_rename_is_super_admin_can_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_admin_roles', to='authentication.instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(related_name='course_admins', through='course.Admin', to='authentication.instructor'),
        ),
    ]
