# Generated by Django 6.0.3 on 2026-04-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('course', '0005_alter_admin_admin_alter_course_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='admin_course', to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='course_admins', through='course.Admin', to='authentication.instructor'),
        ),
    ]
