# Generated by Django 6.0.3 on 2026-04-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_admin_course_alter_course_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
