# Generated by Django 6.0.3 on 2026-05-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_student_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_items',
            field=models.ManyToManyField(blank=True, related_name='completed_items', to='course.content'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress_precentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
