# Generated by Django 6.0.3 on 2026-05-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_enrollment_completed_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='content',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='completed_items',
            field=models.ManyToManyField(blank=True, related_name='completed_by_enrollments', to='course.content'),
        ),
    ]
