# Generated by Django 6.0.3 on 2026-05-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_content_text_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='progress_precentage',
            new_name='progress_percentage',
        ),
    ]
